server:
  port: 8082
spring:
  redis:
    host: 47.96.100.109
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 10000
    password: xcoder

  profiles:
    active: dev

  rabbitmq:
    host: 47.96.100.109
    port: 5672
    username: root
    password: root

  mail:
    host: smtp.qq.com #邮件服务器地址
    port: 465 #端口号
    username: QQ邮箱地址
    password: 上面获取的授权码
    default-encoding: UTF-8 #默认编码格式
    properties:
      mail:
        debug: true #启动debug调试
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory #SSL连接配置