server:
  port: 8082
spring:
  redis:
    host: 47.96.100.109
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 10000
    password: xcoder

  profiles:
    active: dev

  rabbitmq:
    host: 47.96.100.109
    port: 5672
    username: root
    password: root